### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by totora22** [rdoursenaud/Doliwoo#23]
I follow instructions on Dolibarr forum:
http://www.dolibarr.org/forum/505-oscommerce-virtuemart/24055-doliwoo-for-woocomerce#24165

I installed the module with no error, but can't get in and the items are not appearing at woocommerce.

Thanks in advance!

I really would appreciate to make it work... 

Dolibarr 3.5.2
Wordpress 4.0
Woocommerce 2.2.4

**Comment by rdoursenaud** [comment]
This is not a support forum, this is a bug tracker.
The project has moved to https://github.com/GPCsolutions/doliwoo anyway.
